# Base image
FROM python:3.10-slim-buster

# Set the working directory
WORKDIR /app

# Copy application code
COPY . /app

# Install dependencies
RUN apt-get update -y && \
    apt-get install -y awscli && \
    rm -rf /var/lib/apt/lists/* && \
    pip install --no-cache-dir -r requirements.txt

# Default command
CMD ["python3", "app.py"]
